### ISSUE TITLE
V2.0.0 DMG missing favicon.ico

### ISSUE THREAD

**Issue by Tw0bit** [JeffreyDavidsz/VICREO-Listener#26]
Unable to run Version 2.0.0 (downloaded the DMG from releases) - opens a blank page and this error occurs - 

Uncaught Exception:
Error: Image could not be created from /Applications/vicreo.app/Contents/Resources/app.asar/img/favicon.ico
    at App.createWindow (/Applications/vicreo.app/Contents/Resources/app.asar/main.js:24:8)
    at App.emit (events.js:223:5)

**Comment by Tw0bit** [comment]
The zip file when attempting to run the .app says "This application can't be opened."

I have tried to copy the ASAR from the ZIP version to the DMG version and same error of missing ico

**Comment by Tw0bit** [comment]
The .exe version has a 2.7mb ASAR while the Mac is 1.6mb..

I copied the windows ASAR to the Mac but seems not a direct swap and gave even more errors..

Uncaught Exception:
Error: dlopen(/var/folders/sp/wfmr90ds20j43nkcgxzjc3w80000gp/T/.nl.vicreo.listener.mW3Uwb, 1): no suitable image found.  Did find:
	/var/folders/sp/wfmr90ds20j43nkcgxzjc3w80000gp/T/.nl.vicreo.listener.mW3Uwb: unknown file type, first eight bytes: 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00
	/var/folders/sp/wfmr90ds20j43nkcgxzjc3w80000gp/T/.nl.vicreo.listener.mW3Uwb: stat() failed with errno=17
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:738:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Applications/vicreo.app/Contents/Resources/app.asar/node_modules/robotjs/index.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:967:30)

I am not sure how to build it manually for OSX.

**Comment by Tw0bit** [comment]
<img width="394" alt="Screen Shot 2020-06-11 at 1 19 01 pm" src="https://user-images.githubusercontent.com/2338536/84341378-44018700-abe6-11ea-8b0f-370743524114.png">

I have managed to extract the ASAR and it has the ico file... running OSx 10.15.5

**Comment by JeffreyDavidsz** [comment]
Still working on the MAC version, just released a new version
